project:
  type: website
  output-dir: _site

website:
  title: "Shelby Level"
  favicon: logos/sl-hex-sticker.png
  navbar:
    title: "<span class='first-name' >SHELBY</span><span class='icon-line' ></span><span class ='icon-line2'></span> <span class='last-name' >LE</span><span class='v' >v</span> <span class='last-name2' >EL</span>"
    right:
      - href: index.qmd
        text: "About Me"

      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: "Past Projects"
      - icon: github
        href: https://github.com/shelbylevel
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level/
        aria-label: LinkedIn
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Shelby Level"
    right:
      - icon: github
        href: https://github.com/shelbylevel
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level/
  #reader-mode: true

format:
  html:
    theme: [lux, css/sl-styles.scss]
    toc: true
    page-layout: full

editor: source

