---
title: "Character Personalities"
---

Evaluation Questions:
Do characters of the same GOT houses share similar personality traits?
Are there more 'strong' female or male characters in GOT?
Do 'strong' characters hold the most power in Westeros?

```{r packages, include=FALSE}
library(tidyverse)
library(stringr)
library(scales)
library(zoo)
library(sjmisc)
library(janitor)
library(dplyr)
library(tidycensus)
library(tigris)
library(sf)
library(dplyr)
library(classInt)
library(readxl)
library(highcharter)

```

```{r get-data}

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load('2022-08-16')
#tuesdata <- tidytuesdayR::tt_load(2022, week = 33)

characters <- tuesdata$characters
myers_briggs <- tuesdata$myers_briggs
psych_stats <- tuesdata$psych_stats

```

```{r filter-got}

characters %>%
  filter(
    uni_id == 'GOT'
  ) -> characters_got

myers_briggs %>%
  filter(
    uni_id == 'GOT'
    ) -> myers_briggs_got

psych_stats %>%
  filter(
    uni_id == 'GOT'
  ) -> psych_stats_got

```

