---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: SHELBY L LEVEL
    pdf-engine: weasyprint
css: css/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
sl165423@ohio.edu
:::

## Education

**Master of Public Administration** <br> *Ohio University, Voinovich School of Leadership and Public Service* [*July 2023 --- Present*]{.cvdate}

-   Graduate Assistant

**Bachelor of Science in Public Health** <br> *University of Toledo, College of Health and Human Services* [*Aug 2020 --- May 2023*]{.cvdate}

-   Magna cum laude

## Work Experience{style="page-break-before: always"}

### Data Scientist

**Graduate Assistant** <br> *Ohio University, Voinovich School of Leadership and Public Service* [Aug 2023 -- Present]{.cvdate}

Providing 

**Research Staff** <br> *Ohio Alliance for Population Health* [Aug 2023 -- Present]{.cvdate}

Providing 

**Health Policy Intern** <br> *Health Policy Institute of Ohio* [Jan 2023 -- Jun 2023]{.cvdate}

Providing

::: {.no-print}
## CERTIFICATIONS

Certified Health Education Specialist (CHES)

-   Credential ID 38648

:::

::: {.print-only}
## References
Available upon request
:::


## Education

**Ohio University \| Athens, OH** <br> Master of Public Administration \| July 2023 - May 2024

**University of Toledo \| Toledo, OH** <br> B.S in Public Health \| Aug 2020 - May 2023

## Experience

Ohio University Voinovich School of Leadership and Public Service \| Graduate Assistant \| August 2023 - present

Ohio Alliance for Population Health \| Student Employee \| July 2023 - present
